In [1]:

from utils import list_all_files
negative_paths = list(list_all_files('SMILEsmileD-master/SMILEs/negatives/negatives7/', ['.jpg']))
print('loaded', len(negative_paths), 'negative examples')
positive_paths = list(list_all_files('SMILEsmileD-master/SMILEs/positives/positives7/', ['.jpg']))
print('loaded', len(positive_paths), 'positive examples')
examples = [(path, 0) for path in negative_paths] + [(path, 1) for path in positive_paths]

loaded 9475 negative examples
loaded 3690 positive examples


In [2]:
import numpy as np
from skimage.measure import block_reduce
from skimage.io import imread

def examples_to_dataset(examples, block_size=2):
    X = []
    y = []
    for path, label in examples:
        img = imread(path, as_grey=True)
        img = block_reduce(img, block_size=(block_size, block_size), func=np.mean)
        X.append(img)
        y.append(label)
    return np.asarray(X), np.asarray(y)

%time X, y = examples_to_dataset(examples)

Wall time: 7min 27s


In [3]:
print(X[0])

[[129.5  139.5  146.   ... 112.25 101.    75.  ]
 [128.5  134.   141.   ... 121.5  119.25 104.75]
 [125.25 132.5  140.25 ... 121.25 119.5  120.75]
 ...
 [ 71.25  70.5   71.   ...  94.75  79.75  79.25]
 [ 70.25  69.75  71.75 ...  84.5   80.25  68.25]
 [ 71.    69.75  70.75 ...  66.5   65.5   52.25]]


In [4]:

X = X.astype(np.float32) / 255.
y = y.astype(np.int32)
print(X.dtype, X.min(), X.max(), X.shape)
print(y.dtype, y.min(), y.max(), y.shape)

float32 0.0 1.0 (13165, 32, 32)
int32 0 1 (13165,)
