In [11]:
from keras.models import load_model
model = load_model("smile-20.h5")

C:\Users\Bia Martins\Anaconda3\lib\site-packages\theano\tensor\nnet\conv.py:98: UserWarning: theano.tensor.nnet.conv.conv2d is deprecated. Use theano.tensor.nnet.conv2d instead.
  warnings.warn("theano.tensor.nnet.conv.conv2d is deprecated."


In [12]:
from utils import list_all_files
positive_paths = list(list_all_files('SMILEsmileD-master/SMILEs/testes/negativo/', ['.jpg']))
print(positive_paths)

['SMILEsmileD-master/SMILEs/testes/negativo/4.jpg', 'SMILEsmileD-master/SMILEs/testes/negativo/5.jpg', 'SMILEsmileD-master/SMILEs/testes/negativo/7.jpg', 'SMILEsmileD-master/SMILEs/testes/negativo/8.jpg', 'SMILEsmileD-master/SMILEs/testes/negativo/9.jpg']


In [13]:
import numpy as np
from skimage.measure import block_reduce
from skimage.io import imread

def examples_to_dataset(examples, block_size=2):
    X = []
    for path in examples:
        img = imread(path, as_grey=True)
        img = block_reduce(img, block_size=(block_size, block_size), func=np.mean)
        X.append(img)
    return np.asarray(X)

%time X= examples_to_dataset(positive_paths)
X = X.astype(np.float32)/255.
X = np.expand_dims(X, axis=-1)
print(X[0])

Wall time: 225 ms
[[[0.54509807]
  [0.5137255 ]
  [0.6931372 ]
  ...
  [0.6313726 ]
  [0.5882353 ]
  [0.5754902 ]]

 [[0.5901961 ]
  [0.5715686 ]
  [0.6911765 ]
  ...
  [0.6813725 ]
  [0.56666666]
  [0.55588233]]

 [[0.4990196 ]
  [0.6215686 ]
  [0.6617647 ]
  ...
  [0.6745098 ]
  [0.63529414]
  [0.59117645]]

 ...

 [[0.4509804 ]
  [0.52254903]
  [0.16568628]
  ...
  [0.32156864]
  [0.46862745]
  [0.45588234]]

 [[0.5107843 ]
  [0.42843136]
  [0.36960784]
  ...
  [0.3745098 ]
  [0.4617647 ]
  [0.37745097]]

 [[0.74215686]
  [0.41470587]
  [0.44313726]
  ...
  [0.40980393]
  [0.40098038]
  [0.36078432]]]


In [14]:
pred = model.predict_classes(X)
print(pred)

C:\Users\Bia Martins\Anaconda3\lib\site-packages\theano\tensor\nnet\conv.py:98: UserWarning: theano.tensor.nnet.conv.conv2d is deprecated. Use theano.tensor.nnet.conv2d instead.
  warnings.warn("theano.tensor.nnet.conv.conv2d is deprecated."


[0 0 0 0 0]
